update_interval: 600
providers:
  immobilienscout24:
    state: state
    city: city
    districts:
      district: district
google:
  api_key:
  travel_locations:
    alex_work:
      apartment_street:
      apartment_houseNumber:
      apartment_postcode:
      apartment_city:
notifier:
  name: ImmoCrawler
  greeting: You are registered to ImmoCrawler notifications
  token: token