providers:
  immobilienscout24:
    state: Berlin
    city: Berlin
    districts:
      - Prenzlauer-Berg-Prenzlauer-Berg
      - Mitte-Mitte
      - Friedrichshain-Friedrichshain
google:
  api_key:
  travel_locations:
    alex_work:
      apartment_street:
      apartment_houseNumber:
      apartment_postcode:
      apartment_city: