update_interval: 600
providers:
  immobilienscout24:
    state: state
    city: city
filters:
  post_code:
    - 12345
  price_warm:
    min: 100
    max: 200
  living_space:
    min: 10
  travel_time:
    max: 10
google:
  api_key:
  travel_locations:
    - street:
      house_number:
      post_code:
      city:
notifier:
  name: ImmoCrawler
  greeting: You are registered to ImmoCrawler notifications
  token: token