update_interval: 600
providers:
  immobilienscout24:
    state: state
    city: city
    districts:
      district: district
google:
  api_key:
  travel_locations:
    - street:
      house_number:
      post_code:
      city:
notifier:
  name: ImmoCrawler
  greeting: You are registered to ImmoCrawler notifications
  token: token